### ISSUE TITLE
[enhancement] add navigation support (mostly back support) 

### ISSUE THREAD

**Issue by LasneF** [pb33f/doctor#11]
a typical work flow is to explore a deep schema tree, but then  , rollback to the initial definition 

the requirement is to have 'somewhere' a "back" button so that we can rewind the history of navigation

meaning you go to a level you explore x , y z ... and then you want to go back to x , so history of navigation especially that the browser does not handle it here

**Comment by daveshanley** [comment]
Coming soon!


https://github.com/user-attachments/assets/a2584650-97aa-4c92-9a63-d5d861e9208c

**Comment by daveshanley** [comment]
This is now available in the doctor. 

https://github.com/user-attachments/assets/d1e46d2c-3704-4031-9e79-d68dda6b4d77
