### ISSUE TITLE
Highligh Error over warning 

### ISSUE THREAD

**Issue by LasneF** [pb33f/doctor#18]
given 
![image](https://github.com/user-attachments/assets/a681fd69-c2b4-4f09-8bbd-cd6f638a610c)

it would be nicer to have error on top rather than sorting by number of occurence : so error then warning 

or other option ,  highlight in red error in the table to highlight criticality

**Comment by daveshanley** [comment]
This has been added and errors now float to the top and are marked accordingly. 

![Screenshot 2024-11-03 at 2 40 32 PM](https://github.com/user-attachments/assets/bd70fb19-8a7c-4aa0-a4d0-42463706b28a)
