### ISSUE TITLE
Support remote hosted specs

### ISSUE THREAD

**Issue by Gdewilde** [pb33f/doctor#9]
It would be nice to be able to load a spec from the URL like this https://pb33f.io/doctor?spec_url=https://raw.githubusercontent.com/apideck-libraries/openapi-specs/refs/heads/main/crm.yml

**Comment by Gdewilde** [comment]
Awesome!

**Comment by daveshanley** [comment]
It's available now. 

![Screenshot 2024-11-04 at 10 36 50 PM](https://github.com/user-attachments/assets/a86481df-e2a3-43a3-b19a-323173133ef4)

Enter your URL in the box and hit 'fetch'

Or use the url query parameter to auto-load a remote spec into the doctor. for example: https://pb33f.io/doctor/?url=https://api.pb33f.io/wiretap/giftshop-openapi.yaml

**Comment by Gdewilde** [comment]
Thanks for adding this.
